- name: Create Compute Engine instances
  hosts: local
  gather_facts: no
  vars:
    names_zonea: myinstance1,myinstance3
    names_zoneb: myinstance2,myinstance4
    machine_type: n1-standard-1
    image: debian-7
    zonea: us-central1-a
    zoneb: us-central1-b
    pid: YOUR_PROJECT_ID
    email: YOUR_SERVICE_ACCOUNT_EMAIL
    pem: /path/to/your/pkey.pem
  tasks:
    - name: Launch instances in us-central1-a
      local_action: gce instance_names="{{ names_zonea }}"
                    machine_type="{{ machine_type }}"
                    image="{{ image }}" zone="{{ zonea }}"
                    project_id="{{ pid }}" pem_file="{{ pem }}"
                    service_account_email="{{ email }}"
      register: gcea
    - name: Launch instances in us-central1-b
      local_action: gce instance_names="{{ names_zoneb }}"
                    machine_type="{{ machine_type }}"
                    image="{{ image }}" zone="{{ zoneb }}"
                    project_id="{{ pid }}" pem_file="{{ pem }}"
                    service_account_email="{{ email }}"
      register: gceb
    - name: Wait for SSH for instances in zonea
      local_action: wait_for host="{{ item.public_ip }}" port=22 delay=3
                    timeout=60 state=started
      with_items: gcea.instance_data
    - name: Wait for SSH for instances in zoneb
      local_action: wait_for host="{{ item.public_ip }}" port=22 delay=3
                    timeout=60 state=started
      with_items: gceb.instance_data

- name: Install apache, set a custom index.html
  hosts: gce_instances
  sudo: yes
  tasks:
    - name: Install apache
      apt: pkg=apache2 state=present
    - name: Create custom index.html
      copy: dest=/var/www/index.html content='Hi, I am {{ ansible_hostname }}'
    - name: set file stats on index.html
      file: path=/var/www/index.html owner=root group=root mode=0644
    - name: Start apache
      service: name=apache2 state=started

- name: Create a firewall rule to allow HTTP
  hosts: localhost
  gather_facts: no
  vars:
    pid: YOUR_PROJECT_ID
    email: YOUR_SERVICE_ACCOUNT_EMAIL
    pem: /path/to/your/pkey.pem
  tasks:
    - name: Allow HTTP
      local_action: gce_net fwname=all-http name=default allowed=tcp:80
                    project_id="{{ pid }}" pem_file="{{ pem }}"
                    service_account_email="{{ email }}"

- name: Create the Compute Engine Load-balancer
  hosts: localhost
  gather_facts: no
  vars:
    region: us-central1
    members: ["us-central1-a/myinstance1", "us-central1-a/myinstance3",
              "us-central1-b/myinstance2", "us-central1-b/myinstance4"]
    pid: YOUR_PROJECT_ID
    email: YOUR_SERVICE_ACCOUNT_EMAIL
    pem: /path/to/your/pkey.pem
  tasks:
    - name: Create load-balancer
      local_action: gce_lb name=lb region="{{ region }}" members="{{ members }}"
                    project_id="{{ pid }}" pem_file="{{ pem }}"
                    service_account_email="{{ email }}"

